info:
  title: ABCall
  description: ''
  version: 1.0.0
tags:
  - name: testing
basePath: /api
paths:
  /v1/health/client:
    get:
      summary: Health check
      deprecated: false
      description: >-
        This endpoint allows to check the health and availability of the
        ClientService API endpoints. It returns a status code indicating the
        health of the API.
      operationId: healthClient
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: object
            properties:
              status:
                type: string
                description: Status
            required:
              - status
      security: []
      produces:
        - application/json
      x-google-backend:
        address: "${client_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
  /v1/auth/employee:
    post:
      summary: Authenticate employee
      deprecated: false
      description: >-
        Authenticates an employee (administrator, analyst, or agent) and
        generates a JWT authentication token for subsequent API requests.


        - If the user is not found or the password is wrong, the API returns a
        401 Unauthorized error.

        - If the request is not valid JSON or is missing required fields, a 400
        Bad Request error is returned.
      operationId: authEmployee
      tags: []
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              username:
                type: string
                description: The employee's username.
              password:
                type: string
                description: The employee's password.
            required:
              - username
              - password
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: object
            properties:
              token:
                type: string
            required:
              - token
        '400':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
      security: []
      consumes:
        - application/json
      produces:
        - application/json
      x-google-backend:
        address: "${client_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
  /v1/employees:
    post:
      summary: Create employee
      deprecated: false
      description: >-
        Creates a new employee without associating it with a specific client
        initially. Employees can be administrators, analysts, or agents. 

        - If the email address is already registered, the API returns a 409 Conflict error.
        - If the request is not valid JSON or does not meet the field requirements, a 400 Bad Request error is returned.
      operationId: employeeCreate
      tags: [ ]
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the employee.
              email:
                type: string
                description: Email of the employee.
              password:
                type: string
                description: Password for the employee.
              role:
                type: string
                enum:
                  - admin
                  - analyst
                  - agent
                description: Role of the employee.
            required:
              - name
              - email
              - password
              - role
      responses:
        '201':
          description: Employee created successfully
          headers: { }
          schema:
            type: object
            properties:
              id:
                type: string
                description: ID of the employee
              clientId:
                type: string
                description: ID of the associated client (can be null)
              name:
                type: string
                description: Name of the employee
              email:
                type: string
                description: Email of the employee
              role:
                type: string
                description: Role of the employee
            required:
              - id
              - name
              - email
              - role
        '400':
          description: Bad request. The request body is invalid or missing required fields.
          headers: { }
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: Conflict. The email address is already registered.
          headers: { }
          schema:
            $ref: '#/definitions/Error'
      security: [ ]
      consumes:
        - application/json
      produces:
        - application/json
      x-google-backend:
        address: "${client_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS

  /v1/clients:
    get:
      summary: List clients
      deprecated: false
      description: Returns the list of clients (companies)
      operationId: listClients
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                  description: ID of the client
                name:
                  type: string
                  description: Name of the client
              required:
                - id
                - name
      security: []
      produces:
        - application/json
      x-google-backend:
        address: "${client_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
  /v1/clients/{clientId}:
    get:
      summary: Get client
      deprecated: false
      description: Returns information about a client (company)
      operationId: getClient
      tags: []
      parameters:
        - name: clientId
          in: path
          description: ID of the client to retrieve
          required: true
          type: string
          x-example: f0d2e958-f503-462e-b0f1-911c23b2e008
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: object
            properties:
              id:
                type: string
                description: ID of the client
              name:
                type: string
                description: Name of the client
            required:
              - id
              - name
        '400':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
      security: []
      produces:
        - application/json
      x-google-backend:
        address: "${client_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
  /v1/clients/me:
    get:
      summary: Info client
      deprecated: false
      description: >-
        Returns information about the client (company) of the user making the
        request.
      operationId: infoClient
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: object
            properties:
              id:
                type: string
                description: ID of the client
              name:
                type: string
                description: Name of the client
              plan:
                type: string
                description: Plan of the client (only for admins)
              emailIncidents:
                type: string
                description: Email of the client where customers can report incidents
            required:
              - id
              - name
              - emailIncidents
        '401':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
      security:
        - tokenAdmin: []
        - tokenAgent: []
        - tokenAnalyst: []
        - tokenUser: []
      produces:
        - application/json
      x-google-backend:
        address: "${client_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
  /v1/reset/client:
    post:
      summary: Reset database
      deprecated: false
      description: Reset database and optionally load demo data.
      operationId: resetClient
      tags:
        - testing
      parameters:
        - name: demo
          in: query
          description: Set to true to load demo data, false otherwise.
          required: false
          type: boolean
          x-example: false
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: object
            properties:
              status:
                type: string
                description: status
            required:
              - status
      security:
        - tokenDeveloper: []
      produces:
        - application/json
      x-google-backend:
        address: "${client_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
  /v1/employees/me:
    get:
      summary: Info employee
      deprecated: false
      description: Returns information about the employee making the request.
      operationId: infoEmployee
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: object
            properties:
              id:
                type: string
                description: ID of the employee
              clientId:
                type: string
                description: ID of the associated client
              name:
                type: string
                description: Name of the employee
              email:
                type: string
                description: Email of the employee
              role:
                type: string
                description: Role of the employee
            required:
              - id
              - clientId
              - name
              - email
              - role
        '401':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
      security:
        - tokenAdmin: []
        - tokenAgent: []
        - tokenAnalyst: []
      produces:
        - application/json
      x-google-backend:
        address: "${client_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
  /v1/health/user:
    get:
      summary: Health check
      deprecated: false
      description: >-
        This endpoint allows to check the health and availability of the
        UserService API endpoints. It returns a status code indicating the
        health of the API.
      operationId: healthUser
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: object
            properties:
              status:
                type: string
                description: Status
            required:
              - status
      security: []
      produces:
        - application/json
      x-google-backend:
        address: "${user_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
  /v1/auth/user:
    post:
      summary: Authenticate user
      deprecated: false
      description: >-
        Authenticates a user (of a client) and generates a JWT authentication
        token for subsequent API requests.


        - If the user is not found or the password is wrong, the API returns a
        401 Unauthorized error.

        - If the request is not valid JSON or is missing required fields, a 400
        Bad Request error is returned.
      operationId: authUser
      tags: []
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              username:
                type: string
                description: The user's username.
              password:
                type: string
                description: The user's password.
            required:
              - username
              - password
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: object
            properties:
              token:
                type: string
            required:
              - token
        '400':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
      security: []
      consumes:
        - application/json
      produces:
        - application/json
      x-google-backend:
        address: "${user_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
  /v1/reset/user:
    post:
      summary: Reset database
      deprecated: false
      description: Reset database and optionally load demo data.
      operationId: resetUser
      tags:
        - testing
      parameters:
        - name: demo
          in: query
          description: Set to true to load demo data, false otherwise.
          required: false
          type: boolean
          x-example: false
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: object
            properties:
              status:
                type: string
                description: status
            required:
              - status
      security:
        - tokenDeveloper: []
      produces:
        - application/json
      x-google-backend:
        address: "${user_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
  /v1/users/me:
    get:
      summary: User info
      deprecated: false
      description: Returns information about the user making the request.
      operationId: userInfo
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: object
            properties:
              id:
                type: string
                description: ID of the user
              clientId:
                type: string
                description: ID of the associated client
              name:
                type: string
                description: Name of the user
              email:
                type: string
                description: Email of the user
            required:
              - id
              - clientId
              - name
              - email
        '401':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
      security:
        - tokenUser: []
      produces:
        - application/json
      x-google-backend:
        address: "${user_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
  /v1/users:
    post:
      summary: Create user
      deprecated: false
      description: Creates a new user account for a client (company).
      operationId: userCreate
      tags: []
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              clientId:
                type: string
                description: ID of the associated client
              name:
                type: string
                description: Name of the user
              email:
                type: string
                description: Email of the user
              password:
                type: string
                description: Password of the user
            required:
              - clientId
              - name
              - email
              - password
      responses:
        '201':
          description: ''
          headers: {}
          schema:
            type: object
            properties:
              id:
                type: string
                description: ID of the user
              clientId:
                type: string
                description: ID of the associated client
              name:
                type: string
                description: Name of the user
              email:
                type: string
                description: Email of the user
            required:
              - id
              - clientId
              - name
              - email
        '400':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
        '409':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/Error'
      security: []
      consumes:
        - application/json
      produces:
        - application/json
      x-google-backend:
        address: "${user_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
swagger: '2.0'
definitions:
  Error:
    type: object
    properties:
      message:
        type: string
      code:
        type: number
    required:
      - message
      - code
securityDefinitions:
  tokenDeveloper:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "${jwt_issuer}"
    x-google-jwks_uri: "${jwt_jwks}"
    x-google-jwt-locations:
    - header: "Authorization"
      value_prefix: "Bearer "
    x-google-audiences: "developer"
  tokenAdmin:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "${jwt_issuer}"
    x-google-jwks_uri: "${jwt_jwks}"
    x-google-jwt-locations:
    - header: "Authorization"
      value_prefix: "Bearer "
    x-google-audiences: "admin"
  tokenAgent:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "${jwt_issuer}"
    x-google-jwks_uri: "${jwt_jwks}"
    x-google-jwt-locations:
    - header: "Authorization"
      value_prefix: "Bearer "
    x-google-audiences: "agent"
  tokenAnalyst:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "${jwt_issuer}"
    x-google-jwks_uri: "${jwt_jwks}"
    x-google-jwt-locations:
    - header: "Authorization"
      value_prefix: "Bearer "
    x-google-audiences: "analyst"
  tokenUser:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "${jwt_issuer}"
    x-google-jwks_uri: "${jwt_jwks}"
    x-google-jwt-locations:
    - header: "Authorization"
      value_prefix: "Bearer "
    x-google-audiences: "user"
x-components: {}
